### ISSUE TITLE
Gradient from clear to white looks strange

### ISSUE THREAD

**Issue by hokster7** [enormego/EGOGradientView#4]
I've drawn the gradient onto a `UIView` with orange background. The result:
![gradient](https://cloud.githubusercontent.com/assets/430233/9704942/a2897bd8-54ad-11e5-8cdb-90f0a506ef0e.png)

You can quite visibly see a grey band. Why does this happen? I suspect it's because a subtractive blending mode causes this. If Indeed I could switch to additive this shouldn't happen. How might one do this?

**Comment by shnhrrsn** [comment]
I'm going to guess you're using the `clearColor` and `whiteColor` methods on `UIColor`.  Assuming that's true, the reason it's happening is because of what those values actually represent:

* `clearColor` is a fully transparent *black* color
* `whiteColor` is a fully opaque *white* color

So what's happening is the gradient is fading from a transparent black color to an opaque white color, which in the middle is going to be a gray color with 50% transparency.

To get around this, instead of using `clearColor` you can use `colorWithWhite:alpha:` and pass 1.0 for the white value and 0.0 for the alpha value.

Hope this helps!

**Comment by fatuhoku** [comment]
@shnhrrsn Yes! I was going from `clearColor` to `whiteColor`. Virtual insanity man. Code can be a real lie sometimes, can't it!

I thinking about it it does seem obvious now — each of the RGB values are forced to go through the range `0.f` -> `1.0f`, when really I just want them to stay and vary the alpha only.
